# Generated by Django 3.0.8 on 2020-07-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_avatar',
            field=models.CharField(default='Failed to load img', max_length=250),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medium_avatar',
            field=models.CharField(default='Failed to load img', max_length=250),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mini_avatar',
            field=models.CharField(default='Failed to load img', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default=12340987, max_length=100),
        ),
    ]
