# Generated by Django 3.0.8 on 2020-07-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_auto_20200713_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mini_avatar',
        ),
    ]
