# Generated by Django 3.0.8 on 2020-07-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0003_remove_customuser_mini_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
