# Generated by Django 3.0.8 on 2020-08-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0004_auto_20200716_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
