# Generated by Django 3.0.8 on 2020-08-01 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysub', '0002_auto_20200728_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBuySubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount')),
                ('buy_time', models.DateTimeField(default=datetime.datetime(2020, 8, 1, 16, 47, 24, 527203), verbose_name='date')),
            ],
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 16, 47, 24, 526208)),
        ),
    ]
