# Generated by Django 3.0.8 on 2020-08-01 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysub', '0005_auto_20200801_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 17, 0, 13, 377610)),
        ),
        migrations.AlterField(
            model_name='userbuysubscribe',
            name='buy_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 17, 0, 13, 377610), verbose_name='date'),
        ),
    ]
