# Generated by Django 3.0.8 on 2020-08-01 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysub', '0007_auto_20200801_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 17, 29, 11, 840079)),
        ),
        migrations.AlterField(
            model_name='userbuysubscribe',
            name='buy_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 17, 29, 11, 840079), verbose_name='date'),
        ),
    ]
