# Generated by Django 3.0.8 on 2020-08-02 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysub', '0009_auto_20200802_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 9, 37, 5, 894521), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='userbuysubscribe',
            name='buy_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 9, 37, 5, 894521), verbose_name='Date'),
        ),
    ]
